version: '3.1'

services:

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8888:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghostUser
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8888
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: development

  db:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: exampleExtrem
      MARIADB_USER: ghostUser
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: ghost
